# Generated by Django 4.1.7 on 2024-09-24 16:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+989138402864",
                max_length=13,
                region=None,
                verbose_name="phone number",
            ),
        ),
    ]
